apiVersion: v1
kind: Namespace
metadata:
  name: open-data-app
---
apiVersion: v1
kind: Service
metadata:
  name: open-data-service
  namespace: open-data-app
  labels:
    app: open-data-web
spec:
  selector:
    app: open-data-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer